### ISSUE TITLE
NameError: uninitialized constant Pagy::Cursor::DEFAULT

### ISSUE THREAD

**Issue by crazyoptimist** [Uysim/pagy-cursor#48]
I just tried to follow the Usage in README, and got this error.

```bash
E, [2022-12-29T02:19:42.696554 #9116] ERROR -- : NameError: uninitialized constant Pagy::Cursor::DEFAULT

      @vars = DEFAULT.merge(vars.delete_if{|_,v| v.nil? || v == '' })
              ^^^^^^^
  /home/debian/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/pagy_cursor-0.5.0/lib/pagy_cursor/pagy/cursor.rb:9:in `initialize'
  /home/debian/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/pagy_cursor-0.5.0/lib/pagy_cursor/pagy/extras/cursor.rb:8:in `new'
  /home/debian/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/pagy_cursor-0.5.0/lib/pagy_cursor/pagy/extras/cursor.rb:8:in `pagy_cursor'
```

It should look for `Pagy::DEFAULT` instead of `Pagy::Cursor::DEFAULT`. Do you have any idea why this happens?

@Uysim

**Comment by dblock** [comment]
That should be coming from https://github.com/ddnexus/pagy/blob/ffdff1c7b4577ca8deaf38cc66626dfdbb403c6d/lib/pagy.rb#L16, so `Pagy::DEFAULT` instead of `Pagy::Cursor::DEFAULT`. The fix is to change this code to `Pagy::DEFAULT`, but in your code @crazyoptimist I wonder whether `require 'pagy'` first would fix it?

**Comment by crazyoptimist** [comment]
Yes it worked. Thanks!
